spring:
  datasource:
    url: jdbc:postgresql://172.105.109.16:5433/find_hai
    username: postgres
    password: findhai
    hikari:
      maximum-pool-size: '10'
      connection-timeout: '60000'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format:
          sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  application:
    name: FindHaiApplication
server:
  port: '8090'

logging:
  level:
    org:
      springframework: DEBUG
      hibernate: DEBUG
