spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/find_hai
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: FindHaiApplication

server:
  port: 8091

#logging:
#  level:
#    org:
#      springframework: INFO
#      hibernate: INFO

